steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/wall-paper-map-backend/demo-app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/wall-paper-map-backend/demo-app']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'demo-app', '--image', 'gcr.io/wall-paper-map-backend/demo-app', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated']

images:
- 'gcr.io/wall-paper-map-backend/demo-app'
