services:
  app:
    build: .
    volumes:
      - .:/src
    ports:
      - "8000:8000"
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/app-image', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/app-image']
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy app-service --image gcr.io/$PROJECT_ID/app-image --region us-central1 --platform managed --allow-unauthenticated
images:
  - 'gcr.io/$PROJECT_ID/app-image'
